### ISSUE TITLE
Every SubAssembly should define upstream Pipes

### ISSUE THREAD

**Issue by Schmed** [ScaleUnlimited/cascading.classify#11]
The following SubAssembly classes need to pass their upstream Pipes to the super constructor. Otherwise, setStepConfigDef (among other things) won't work properly (see https://groups.google.com/forum/#!searchin/cascading-user/consequences$20setprevious/cascading-user/bp9zlbZUa1s/kOsCimu8OioJ for more details).

1. https://github.com/ScaleUnlimited/cascading.classify/blob/master/src/main/java/com/scaleunlimited/classify/pu/AnalyzeTrainingDataPipe.java
1. https://github.com/ScaleUnlimited/cascading.classify/blob/master/src/main/java/com/scaleunlimited/classify/ClassifyDocsPipe.java
1. https://github.com/ScaleUnlimited/cascading.classify/blob/master/src/main/java/com/scaleunlimited/classify/pu/GetRNThresholdPipe.java
1. https://github.com/ScaleUnlimited/cascading.classify/blob/master/src/main/java/com/scaleunlimited/classify/pu/TrainFinalModelPipe.java
1. https://github.com/ScaleUnlimited/cascading.classify/blob/master/src/main/java/com/scaleunlimited/classify/TrainLogisticModelPipe.java
1. https://github.com/ScaleUnlimited/cascading.classify/blob/master/src/main/java/com/scaleunlimited/classify/TrainModelPipe.java
1. https://github.com/ScaleUnlimited/cascading.classify/blob/master/src/main/java/com/scaleunlimited/classify/pu/TrainSpyModelPipe.java

**Comment by vmagotra** [comment]
Done.
